//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IRON_PROGRAMMER_BOT_Common {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IRON_PROGRAMMER_BOT_Common.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] bot_3 {
            get {
                object obj = ResourceManager.GetObject("bot_3", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В нашей школе ты найдешь курсы для &lt;u&gt;любого&lt;/u&gt; уровня подготвки. 
        ///Как для школьников и студентов, так и для тех, кто думает о смене професии, и для тех, кто уже уверненно идет по этому пути.
        /// </summary>
        public static string CommonCoursesPageText {
            get {
                return ResourceManager.GetString("CommonCoursesPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вот курсы по C#.
        /// </summary>
        public static string CSharpCoursesPageText {
            get {
                return ResourceManager.GetString("CSharpCoursesPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;МОЗГОКАЧАЛКА&lt;/b&gt;
        ///Мозгокачалка это мощный проект для наших учеников, для мотивации к новым достижениям! 
        ///Занимайся каждый день, участвуй в мозгокачалке и не только стань самым умным, но и получай крутые призы!.
        /// </summary>
        public static string MozgokachalkaPageText {
            get {
                return ResourceManager.GetString("MozgokachalkaPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для того, чтобы принять участие в мозгокачалке необходимо каждый день в течние календарного месяца решать миниму одну задачу на Степике. 
        ///На каких именно курсах - &lt;b&gt;на твоё усмотрение&lt;/b&gt;. Каждый месяц среди прошедших этот челлендж разыгрывается крутой мерч. 
        ///&lt;u&gt;Учатсие в мозгокачалке бесплатное.&lt;/u&gt;&quot;.
        /// </summary>
        public static string MozgokachalkaRulesPageText {
            get {
                return ResourceManager.GetString("MozgokachalkaRulesPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Курсы для тех, кто хочет попробовать свои силы в программировании и размышляет над будущей профессие разработчика. Начни с:
        ///            * &lt;a href=&quot;https://stepik.org/course/50659/promo?auth=login&quot;&gt;Подготовка к ОГЭ по информатике &lt;/a&gt;           
        ///            * &lt;a href=&quot;https://stepik.org/course/49808/promo?auth=login&quot;&gt;Тренировочные варианты ЕГЭ по информатике &lt;/a&gt;           
        ///            * &lt;a href=&quot;https://stepik.org/course/30058/promo?auth=login&quot;&gt;ЕГЭ по информатике: B часть (1 - 23 задания)&lt;/a&gt;
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        public static string OgeAndEgePageText {
            get {
                return ResourceManager.GetString("OgeAndEgePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверное значение Stepik ID. Пожалуйста, введите ID в цифровом значении.
        /// </summary>
        public static string RegistrationPageIncorrectStepikIDText {
            get {
                return ResourceManager.GetString("RegistrationPageIncorrectStepikIDText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для регистрации отправьте свой &lt;b&gt;Stepik ID&lt;/b&gt;. Его можно найти в своём профиле на сайте &lt;a href=&quot;https://stepik.org/catalog&quot;&gt;Stepik&lt;/a&gt;.
        /// </summary>
        public static string RegistrationPageText {
            get {
                return ResourceManager.GetString("RegistrationPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;Привет!&lt;/b&gt;
        ///Рад видеть тебя😊
        ///
        ///Задай свой вопрос и я тебе обязательно отвечу!
        ///
        ///Хочешь записаться на курс или получить информацию?
        ///Нажми одну из кнопок ниже, выбирай направление - я отвечу и помогу тебе😉.
        /// </summary>
        public static string StartPageText {
            get {
                return ResourceManager.GetString("StartPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователь зарегистрирован, добро пожаловать в группу: 
        ///
        ///https://t.me/+WMb4-xV3n3QyMWIy.
        /// </summary>
        public static string SuccessfulRegistrationPageText {
            get {
                return ResourceManager.GetString("SuccessfulRegistrationPageText", resourceCulture);
            }
        }
    }
}
